# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
